### PR TITLE
ScreenObtainer:  Use echoCancellation: true Optional Audio Constraint With Electron Screen Sharing With Audio 

### PR DESCRIPTION
**Pull request by WesUnwin**

### CODE REVIEW

**Review by jerry2013 — DISMISSED** [review]
This is fine - only it won't do anything without compiling your own chromium in electron.

**Comment by WesUnwin** [comment]
Sounds good, let me know when it gets merged / and if you want me to do anything to introduce it on facetalk.

Would be good to test whether this possibly would work, but ya I see that it may not work without the underlying electron fix.

Would be good to test anyway, maybe I can even build jitsi and test it on my facetalk vm.

**Comment by jerry2013** [comment]
It won't work without chromium change.

Building lib-jitsi to test is not hard, just npm i && npm build, then change your facetalk to use local (e.g. "...": "file:../foo/bar")

**Comment by WesUnwin** [comment]
Yes It probably won't work, but would be good closure to quickly test just to confirm it indeed does not work. I'll sometime give it a quick test, or just wait for this to be merged

**Comment by jerry2013** [comment]
using gUM for desktop audio needs to be

```
    audio : {
        mandatory: {
            echoCancellation: true,
            chromeMediaSource: 'desktop'
          }
    },
```

**Pull request closed without merging**
